import { PERMISSIONS, type Permission } from "./permissionKeys"
import type { UserRole } from "./types"

const EDM_PROFILE_VIEW: readonly Permission[] = [
  PERMISSIONS.EMPLOYEES_PROFILE_PERSONAL,
  PERMISSIONS.EMPLOYEES_PROFILE_EMPLOYMENT,
  PERMISSIONS.EMPLOYEES_PROFILE_COMPENSATION,
  PERMISSIONS.EMPLOYEES_PROFILE_GOVERNMENT,
  PERMISSIONS.EMPLOYEES_PROFILE_DOCUMENTS,
  PERMISSIONS.EMPLOYEES_PROFILE_COMPLIANCE,
  PERMISSIONS.EMPLOYEES_PROFILE_ACCESS,
  PERMISSIONS.EMPLOYEES_PROFILE_TIME_OFF,
]

const HR_SENSITIVE_VIEW: readonly Permission[] = [
  PERMISSIONS.EMPLOYEES_PROFILE_PAY,
  PERMISSIONS.EMPLOYEES_PROFILE_PERFORMANCE,
]

const EMPLOYEE_PERMISSIONS: readonly Permission[] = [
  PERMISSIONS.DASHBOARD_VIEW,
  PERMISSIONS.EMPLOYEES_VIEW_OWN,
  PERMISSIONS.EMPLOYEES_PROFILE_PERSONAL,
  PERMISSIONS.EMPLOYEES_PROFILE_EMPLOYMENT,
  PERMISSIONS.EMPLOYEES_PROFILE_COMPENSATION,
  PERMISSIONS.EMPLOYEES_PROFILE_GOVERNMENT,
  PERMISSIONS.EMPLOYEES_PROFILE_DOCUMENTS,
  PERMISSIONS.EMPLOYEES_PROFILE_COMPLIANCE,
  PERMISSIONS.EMPLOYEES_PROFILE_TIME_OFF,
  PERMISSIONS.EMPLOYEES_PROFILE_SELF_SERVICE,
  PERMISSIONS.SETTINGS_THEME,
]

const MANAGER_PERMISSIONS: readonly Permission[] = [
  PERMISSIONS.DASHBOARD_VIEW,
  PERMISSIONS.EMPLOYEES_VIEW_DIRECTORY,
  PERMISSIONS.EMPLOYEES_VIEW_OWN,
  PERMISSIONS.EMPLOYEES_PROFILE_PERSONAL,
  PERMISSIONS.EMPLOYEES_PROFILE_EMPLOYMENT,
  PERMISSIONS.EMPLOYEES_PROFILE_DOCUMENTS,
  PERMISSIONS.EMPLOYEES_PROFILE_ACCESS,
  PERMISSIONS.EMPLOYEES_PROFILE_TIME_OFF,
  PERMISSIONS.EMPLOYEES_PROFILE_SELF_SERVICE,
  PERMISSIONS.SETTINGS_THEME,
  PERMISSIONS.LEAVE_APPROVE,
]

const HRBP_PERMISSIONS: readonly Permission[] = [
  PERMISSIONS.DASHBOARD_VIEW,
  PERMISSIONS.EMPLOYEES_VIEW_DIRECTORY,
  ...EDM_PROFILE_VIEW,
  PERMISSIONS.EMPLOYEES_PROFILE_SELF_SERVICE,
  PERMISSIONS.SETTINGS_THEME,
]

const HR_ADMIN_PERMISSIONS: readonly Permission[] = [
  PERMISSIONS.DASHBOARD_VIEW,
  PERMISSIONS.EMPLOYEES_VIEW_DIRECTORY,
  PERMISSIONS.EMPLOYEES_CREATE,
  PERMISSIONS.EMPLOYEES_DELETE,
  ...EDM_PROFILE_VIEW,
  ...HR_SENSITIVE_VIEW,
  PERMISSIONS.SETTINGS_VIEW,
  PERMISSIONS.SETTINGS_THEME,
  PERMISSIONS.BILLING_MANAGE,
]

const HRIS_SUPER_ADMIN_PERMISSIONS: readonly Permission[] = [
  ...HR_ADMIN_PERMISSIONS,
  PERMISSIONS.USERS_MANAGE,
  PERMISSIONS.RBAC_MANAGE,
  PERMISSIONS.AUDIT_VIEW,
]

const SYSTEM_ADMIN_PERMISSIONS: readonly Permission[] = [
  PERMISSIONS.DASHBOARD_VIEW,
  PERMISSIONS.EMPLOYEES_VIEW_DIRECTORY,
  PERMISSIONS.EMPLOYEES_PROFILE_PERSONAL,
  PERMISSIONS.EMPLOYEES_PROFILE_EMPLOYMENT,
  PERMISSIONS.EMPLOYEES_PROFILE_DOCUMENTS,
  PERMISSIONS.EMPLOYEES_PROFILE_ACCESS,
  PERMISSIONS.EMPLOYEES_PROFILE_COMPLIANCE,
  PERMISSIONS.SETTINGS_VIEW,
  PERMISSIONS.SETTINGS_THEME,
  PERMISSIONS.AUDIT_VIEW,
]

export const DEFAULT_ROLE_PERMISSIONS: Record<UserRole, readonly Permission[]> = {
  employee: EMPLOYEE_PERMISSIONS,
  manager: MANAGER_PERMISSIONS,
  hrbp: HRBP_PERMISSIONS,
  hris_admin: HR_ADMIN_PERMISSIONS,
  hris_super_admin: HRIS_SUPER_ADMIN_PERMISSIONS,
  system_admin: SYSTEM_ADMIN_PERMISSIONS,
}

export function getDefaultPermissionsForRole(role: UserRole): readonly Permission[] {
  return DEFAULT_ROLE_PERMISSIONS[role]
}
