import type { EdmFieldDefinition } from "./types"

/** EDM field registry — source of truth for tab, sensitivity, and edit authority */
export const EDM_FIELD_REGISTRY: EdmFieldDefinition[] = [
  {
    key: "employeeId",
    label: "Employee ID",
    tab: "personal",
    sensitivity: "internal",
    editAuthority: "system",
    approvalRequired: false,
  },
  {
    key: "name",
    label: "Name",
    tab: "personal",
    sensitivity: "confidential",
    editAuthority: "hris_admin",
    approvalRequired: true,
  },
  {
    key: "preferredName",
    label: "Preferred Name",
    tab: "personal",
    sensitivity: "internal",
    editAuthority: "employee",
    approvalRequired: false,
  },
  {
    key: "employeePhoto",
    label: "Employee Photo",
    tab: "personal",
    sensitivity: "confidential",
    editAuthority: "employee",
    approvalRequired: false,
  },
  {
    key: "demographics",
    label: "Gender, Birthdate, Civil Status",
    tab: "personal",
    sensitivity: "confidential",
    editAuthority: "hris_admin",
    approvalRequired: true,
  },
  {
    key: "contact",
    label: "Email & Contact Number",
    tab: "personal",
    sensitivity: "confidential",
    editAuthority: "employee",
    approvalRequired: false,
  },
  {
    key: "address",
    label: "Home Address",
    tab: "personal",
    sensitivity: "confidential",
    editAuthority: "employee",
    approvalRequired: false,
  },
  {
    key: "emergencyContact",
    label: "Emergency Contact",
    tab: "personal",
    sensitivity: "confidential",
    editAuthority: "employee",
    approvalRequired: false,
  },
  {
    key: "departmentPosition",
    label: "Department & Position",
    tab: "employment",
    sensitivity: "internal",
    editAuthority: "hrbp",
    approvalRequired: true,
  },
  {
    key: "supervisor",
    label: "Supervisor / Manager",
    tab: "employment",
    sensitivity: "internal",
    editAuthority: "hrbp",
    approvalRequired: true,
  },
  {
    key: "managerEmployeeId",
    label: "Manager Employee ID",
    tab: "employment",
    sensitivity: "internal",
    editAuthority: "system",
    approvalRequired: false,
  },
  {
    key: "orgStructure",
    label: "Organization Level, Business Unit, Cost Center",
    tab: "employment",
    sensitivity: "internal",
    editAuthority: "hrbp",
    approvalRequired: true,
  },
  {
    key: "workLocation",
    label: "Work Location",
    tab: "employment",
    sensitivity: "internal",
    editAuthority: "hrbp",
    approvalRequired: true,
  },
  {
    key: "employmentType",
    label: "Employment Type",
    tab: "employment",
    sensitivity: "internal",
    editAuthority: "hris_admin",
    approvalRequired: true,
  },
  {
    key: "employeeStatus",
    label: "Employee Status",
    tab: "employment",
    sensitivity: "internal",
    editAuthority: "hris_admin",
    approvalRequired: true,
  },
  {
    key: "dateHired",
    label: "Date Hired",
    tab: "employment",
    sensitivity: "internal",
    editAuthority: "hris_admin",
    approvalRequired: true,
  },
  {
    key: "dateContractSigned",
    label: "Date Contract Signed",
    tab: "employment",
    sensitivity: "confidential",
    editAuthority: "hris_admin",
    approvalRequired: true,
  },
  {
    key: "probationRegularization",
    label: "End of Probation & Regularization Date",
    tab: "employment",
    sensitivity: "internal",
    editAuthority: "hris_admin",
    approvalRequired: true,
  },
  {
    key: "terminationDate",
    label: "Date Resigned / Terminated",
    tab: "employment",
    sensitivity: "confidential",
    editAuthority: "hris_admin",
    approvalRequired: true,
  },
  {
    key: "separationReason",
    label: "Separation Reason",
    tab: "employment",
    sensitivity: "restricted",
    editAuthority: "hris_admin",
    approvalRequired: true,
  },
  {
    key: "monthlySalary",
    label: "Monthly Salary",
    tab: "compensation",
    sensitivity: "restricted",
    editAuthority: "payroll",
    approvalRequired: true,
  },
  {
    key: "salaryGrade",
    label: "Salary Grade",
    tab: "compensation",
    sensitivity: "confidential",
    editAuthority: "cb",
    approvalRequired: true,
  },
  {
    key: "compensationEffectiveDate",
    label: "Compensation Effective Date",
    tab: "compensation",
    sensitivity: "confidential",
    editAuthority: "cb",
    approvalRequired: true,
  },
  {
    key: "hmoCoverage",
    label: "HMO Coverage / Status",
    tab: "compensation",
    sensitivity: "restricted",
    editAuthority: "hris_admin",
    approvalRequired: false,
  },
  {
    key: "governmentIds",
    label: "TIN, SSS, PhilHealth, Pag-IBIG",
    tab: "government",
    sensitivity: "restricted",
    editAuthority: "hris_admin",
    approvalRequired: false,
  },
  {
    key: "uploadedDocuments",
    label: "Uploaded Files",
    tab: "documents",
    sensitivity: "restricted",
    editAuthority: "hris_admin",
    approvalRequired: false,
  },
  {
    key: "documentMetadata",
    label: "Document Metadata",
    tab: "documents",
    sensitivity: "internal",
    editAuthority: "system",
    approvalRequired: false,
  },
  {
    key: "onboardingChecklist",
    label: "Onboarding Checklist Status",
    tab: "documents",
    sensitivity: "internal",
    editAuthority: "hris_admin",
    approvalRequired: false,
  },
  {
    key: "privacyConsent",
    label: "Data Privacy Consent",
    tab: "compliance",
    sensitivity: "restricted",
    editAuthority: "employee",
    approvalRequired: false,
  },
  {
    key: "dataSubjectAccess",
    label: "Data Subject Access Signed",
    tab: "compliance",
    sensitivity: "restricted",
    editAuthority: "employee",
    approvalRequired: false,
  },
  {
    key: "retentionDeletion",
    label: "Retention Period & Date of Data Deletion",
    tab: "compliance",
    sensitivity: "restricted",
    editAuthority: "dpo",
    approvalRequired: true,
  },
  {
    key: "auditTrail",
    label: "Created / Updated Audit",
    tab: "compliance",
    sensitivity: "internal",
    editAuthority: "system",
    approvalRequired: false,
  },
  {
    key: "systemAccess",
    label: "Access to Company Systems",
    tab: "access",
    sensitivity: "restricted",
    editAuthority: "it",
    approvalRequired: true,
  },
  {
    key: "accessRequestStatus",
    label: "Access Request Status",
    tab: "access",
    sensitivity: "internal",
    editAuthority: "it",
    approvalRequired: true,
  },
  {
    key: "provisionDates",
    label: "Provisioned / Deprovisioned Dates",
    tab: "access",
    sensitivity: "restricted",
    editAuthority: "it",
    approvalRequired: true,
  },
]

export const EDM_FIELD_MAP = Object.fromEntries(
  EDM_FIELD_REGISTRY.map(f => [f.key, f])
) as Record<
  (typeof EDM_FIELD_REGISTRY)[number]["key"],
  EdmFieldDefinition
>

export function getFieldsForTab(tab: EdmFieldDefinition["tab"]) {
  return EDM_FIELD_REGISTRY.filter(f => f.tab === tab)
}

export function getFieldDefinition(key: EdmFieldDefinition["key"]) {
  return EDM_FIELD_MAP[key]
}
