import type { EdmFieldKey, FieldAccessLevel, RoleMatrixEntry } from "./types"

/** Per-field RBAC matrix from EDM spec */
export const EDM_ROLE_MATRIX: Record<EdmFieldKey, RoleMatrixEntry> = {
  employeeId: {
    system_admin: "view",
    hris_super_admin: "edit",
    hris_admin: "edit",
    hrbp: "view",
    manager: "view_team",
    employee: "view_own",
  },
  name: {
    system_admin: "hidden",
    hris_super_admin: "edit",
    hris_admin: "edit",
    hrbp: "view",
    manager: "limited_view",
    employee: "edit_own",
  },
  preferredName: {
    system_admin: "view",
    hris_super_admin: "edit",
    hris_admin: "edit",
    hrbp: "view",
    manager: "view_team",
    employee: "view_own",
  },
  employeePhoto: {
    system_admin: "hidden",
    hris_super_admin: "edit",
    hris_admin: "edit",
    hrbp: "view",
    manager: "limited_view",
    employee: "edit_own",
  },
  demographics: {
    system_admin: "hidden",
    hris_super_admin: "edit",
    hris_admin: "edit",
    hrbp: "view",
    manager: "limited_view",
    employee: "edit_own",
  },
  contact: {
    system_admin: "hidden",
    hris_super_admin: "edit",
    hris_admin: "edit",
    hrbp: "view",
    manager: "limited_view",
    employee: "edit_own",
  },
  address: {
    system_admin: "hidden",
    hris_super_admin: "edit",
    hris_admin: "edit",
    hrbp: "view",
    manager: "limited_view",
    employee: "edit_own",
  },
  emergencyContact: {
    system_admin: "hidden",
    hris_super_admin: "edit",
    hris_admin: "edit",
    hrbp: "view",
    manager: "limited_view",
    employee: "edit_own",
  },
  departmentPosition: {
    system_admin: "view",
    hris_super_admin: "edit",
    hris_admin: "edit",
    hrbp: "view",
    manager: "view_team",
    employee: "view_own",
  },
  supervisor: {
    system_admin: "view",
    hris_super_admin: "edit",
    hris_admin: "edit",
    hrbp: "view",
    manager: "view_team",
    employee: "view_own",
  },
  managerEmployeeId: {
    system_admin: "view",
    hris_super_admin: "edit",
    hris_admin: "edit",
    hrbp: "view",
    manager: "view_team",
    employee: "view_own",
  },
  orgStructure: {
    system_admin: "view",
    hris_super_admin: "edit",
    hris_admin: "edit",
    hrbp: "view",
    manager: "view_team",
    employee: "view_own",
  },
  workLocation: {
    system_admin: "view",
    hris_super_admin: "edit",
    hris_admin: "edit",
    hrbp: "view",
    manager: "view_team",
    employee: "view_own",
  },
  employmentType: {
    system_admin: "view",
    hris_super_admin: "edit",
    hris_admin: "edit",
    hrbp: "view",
    manager: "view_team",
    employee: "view_own",
  },
  employeeStatus: {
    system_admin: "view",
    hris_super_admin: "edit",
    hris_admin: "edit",
    hrbp: "view",
    manager: "view_team",
    employee: "view_own",
  },
  dateHired: {
    system_admin: "view",
    hris_super_admin: "edit",
    hris_admin: "edit",
    hrbp: "view",
    manager: "view_team",
    employee: "view_own",
  },
  dateContractSigned: {
    system_admin: "hidden",
    hris_super_admin: "edit",
    hris_admin: "edit",
    hrbp: "view",
    manager: "limited_view",
    employee: "view_own",
  },
  probationRegularization: {
    system_admin: "view",
    hris_super_admin: "edit",
    hris_admin: "edit",
    hrbp: "view",
    manager: "view_team",
    employee: "view_own",
  },
  terminationDate: {
    system_admin: "hidden",
    hris_super_admin: "edit",
    hris_admin: "edit",
    hrbp: "view",
    manager: "limited_view",
    employee: "view_own",
  },
  separationReason: {
    system_admin: "hidden",
    hris_super_admin: "edit",
    hris_admin: "edit",
    hrbp: "view",
    manager: "hidden",
    employee: "view_own",
  },
  monthlySalary: {
    system_admin: "hidden",
    hris_super_admin: "edit",
    hris_admin: "edit",
    hrbp: "view",
    manager: "hidden",
    employee: "view_own",
  },
  salaryGrade: {
    system_admin: "hidden",
    hris_super_admin: "edit",
    hris_admin: "edit",
    hrbp: "view",
    manager: "limited_view",
    employee: "edit_own",
  },
  compensationEffectiveDate: {
    system_admin: "hidden",
    hris_super_admin: "edit",
    hris_admin: "edit",
    hrbp: "view",
    manager: "limited_view",
    employee: "edit_own",
  },
  hmoCoverage: {
    system_admin: "hidden",
    hris_super_admin: "edit",
    hris_admin: "edit",
    hrbp: "view",
    manager: "hidden",
    employee: "view_own",
  },
  governmentIds: {
    system_admin: "hidden",
    hris_super_admin: "edit",
    hris_admin: "edit",
    hrbp: "view",
    manager: "hidden",
    employee: "view_own",
  },
  uploadedDocuments: {
    system_admin: "hidden",
    hris_super_admin: "edit",
    hris_admin: "edit",
    hrbp: "view",
    manager: "hidden",
    employee: "view_own",
  },
  documentMetadata: {
    system_admin: "view",
    hris_super_admin: "edit",
    hris_admin: "edit",
    hrbp: "view",
    manager: "view_team",
    employee: "view_own",
  },
  onboardingChecklist: {
    system_admin: "view",
    hris_super_admin: "edit",
    hris_admin: "edit",
    hrbp: "view",
    manager: "view_team",
    employee: "view_own",
  },
  privacyConsent: {
    system_admin: "hidden",
    hris_super_admin: "edit",
    hris_admin: "edit",
    hrbp: "view",
    manager: "hidden",
    employee: "view_own",
  },
  dataSubjectAccess: {
    system_admin: "hidden",
    hris_super_admin: "edit",
    hris_admin: "edit",
    hrbp: "view",
    manager: "hidden",
    employee: "view_own",
  },
  retentionDeletion: {
    system_admin: "hidden",
    hris_super_admin: "edit",
    hris_admin: "edit",
    hrbp: "view",
    manager: "hidden",
    employee: "view_own",
  },
  auditTrail: {
    system_admin: "view",
    hris_super_admin: "edit",
    hris_admin: "edit",
    hrbp: "view",
    manager: "view_team",
    employee: "view_own",
  },
  systemAccess: {
    system_admin: "hidden",
    hris_super_admin: "edit",
    hris_admin: "edit",
    hrbp: "view",
    manager: "hidden",
    employee: "view_own",
  },
  accessRequestStatus: {
    system_admin: "view",
    hris_super_admin: "edit",
    hris_admin: "edit",
    hrbp: "view",
    manager: "view_team",
    employee: "view_own",
  },
  provisionDates: {
    system_admin: "hidden",
    hris_super_admin: "edit",
    hris_admin: "edit",
    hrbp: "view",
    manager: "hidden",
    employee: "view_own",
  },
}

export function getMatrixLevel(
  fieldKey: EdmFieldKey,
  role: keyof RoleMatrixEntry
): FieldAccessLevel {
  return EDM_ROLE_MATRIX[fieldKey][role]
}
